import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://api.openweathermap.org/data/2.5/weather?q=Vienna&units=metric&lang=de&APPID=bc004243ecd78e40621876d43e03c2f9
  `);
  const data = await res.json();
  
  // Pass data to the page via props
  return { props: { data } }
}

function convertToDate(timestamp) {
  const time = new Date(timestamp * 1000);

  const weekDays = ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'];

  const months = ['Januar', 'Februar', 'Maerz', 'April', 'Mai', 'Jun', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'];
  const month = months[time.getMonth()];

  const date = time.getDate();

  return weekDays[time.getUTCDay()] + ' ' + date + '.' + month + ' ' + time.getFullYear();
}

function styleTemperature(temp) {
  return temp + '°C';
}

function styleFeeledTemperature(temp) {
  return 'gefühlte Temperatur: ' + styleTemperature(temp);
}

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.grid}>

        <div className={styles.item1}>
          <h2>{data.name}</h2>
          <div>{convertToDate(data.dt)}</div>
        </div>
       
        <div className={styles.image}>
        <Image src={`http://openweathermap.org/img/wn/${data.weather[0].icon}@2x.png`}
              alt="weather icon"
              width={100}
              height={100}
            />
          </div>
          <div>
            <h1>{styleTemperature(Math.ceil(data.main.temp_max))}</h1>
            <h2>{styleTemperature(Math.ceil(data.main.temp_min))}</h2>
            <div>{data.weather[0].description}</div>
            <div>{styleFeeledTemperature(Math.ceil(data.main.feels_like))}</div>
          </div>
        
      </main>
    </>
  )
}