import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://api.openweathermap.org/data/2.5/weather?q=Vienna&units=metric&APPID=bc004243ecd78e40621876d43e03c2f9
  `);
  const data = await res.json();
  
  // Pass data to the page via props
  return { props:  { data } }
}

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

      {data.main.temp}



      </main>
    </>
  )
}


